# Generated by Django 3.1.1 on 2020-10-05 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_control', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Stock',
            new_name='Producto',
        ),
    ]
