# Generated by Django 3.1.1 on 2020-10-13 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_control', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
