# Generated by Django 3.1.1 on 2020-10-13 07:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_control', '0002_auto_20201013_0304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categoría',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Despensa'), (2, 'Bebidas'), (3, 'Mascotas'), (4, 'Bebés'), (5, 'Cuidado Personal'), (6, 'Limpieza'), (7, 'Tecnología')], default=1),
        ),
        migrations.AlterField(
            model_name='producto',
            name='código',
            field=models.CharField(max_length=13, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^[1-9]^\\d{1,13}$')]),
        ),
    ]
