# Generated by Django 3.1.1 on 2020-10-05 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_control', '0003_auto_20201005_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='código',
            field=models.BigIntegerField(blank=True, max_length=13, null=True),
        ),
    ]
