# Generated by Django 3.1.1 on 2020-10-05 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_control', '0004_auto_20201005_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imágen',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='producto',
            name='cantidad',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='código',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(default='Producto', max_length=50),
        ),
    ]
