# Generated by Django 3.1.1 on 2020-10-13 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_control', '0004_auto_20201013_0406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categoría',
            field=models.CharField(choices=[('Despensa', 'Despensa'), ('Bebidas', 'Bebidas'), ('Mascotas', 'Mascotas'), ('Bebés', 'Bebés'), ('Cuidado Personal', 'Cuidado Personal'), ('Limpieza', 'Limpieza'), ('Tecnología', 'Tecnología')], default=1, max_length=50),
        ),
    ]
