# Generated by Django 3.1.1 on 2020-10-11 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_control', '0005_auto_20201005_1705'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='imágen',
            new_name='imagen',
        ),
    ]
