# Generated by Django 3.1.1 on 2020-10-17 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_control', '0005_auto_20201013_0411'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoría',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='producto',
            name='categoría',
        ),
        migrations.AddField(
            model_name='producto',
            name='categoría',
            field=models.ManyToManyField(to='stock_control.Categoría'),
        ),
    ]
