# Generated by Django 3.1.1 on 2020-10-17 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_control', '0007_auto_20201017_0423'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categoria',
            new_name='Categoría',
        ),
    ]
