# Generated by Django 3.1.1 on 2020-10-17 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_control', '0008_auto_20201017_0424'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categoría',
            new_name='Categoria',
        ),
    ]
