# Generated by Django 3.1.1 on 2020-10-19 04:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_control', '0010_auto_20201017_0428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='código',
            field=models.CharField(max_length=13, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^.{13}$', '^\\d{1,13}$')]),
        ),
    ]
